[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "LGPL-3.0", "MIT", "Unicode-3.0", "Zlib"]

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0320", reason = "unmaintained yaml-rust is not critical" },
    { id = "RUSTSEC-2024-0436", reason = "unmaintained paste is not critical" },
]
